---
ansible_host: 172.16.252.3
ansible_timeout: 30
loopback_interface:
  name: loopback0
  ip_address: 1.1.1.1
  subnet_mask: 255.255.255.255

bgp:
  ebgp_interface_name: Ethernet2/0
  ebgp_ip_address: 100.0.0.5
  ebgp_subnet_mask: 255.255.255.252
  AS : 64000
  ebgp_neighbor_ip : 100.0.0.6
  ebgp_neighbor_AS : 65000
...